### PR TITLE
Add framework target

### PR DESCRIPTION
**Pull request by shritekale**
This PR allows us to build the code as a dynamic framework to link into apps that don't use CocoaPods.  Should give carthage support for free as well, for people going that route.

### CODE REVIEW

**Comment by daveverwer** [comment]
Looks good and I'd be happy for this to be merged. Might be worth a mention in the README if you want to add something?

**Comment by shritekale** [comment]
@daveverwer Updated README file.

**Comment by daveverwer** [comment]
I'll get this merged at the weekend, thanks very much for the contribution!

**Comment by shritekale** [comment]
This would lead to potential app rejection from Apple since the library built is universal for simulator and device. Therefore closing this PR without merging.

**Comment by danielbmarques** [comment]
@shritekale Carthage has a Run Script Build Phase to fix that problem and it would be nice to have Carthage support.

**Comment by daveverwer** [comment]
Apologies, I never did respond to this after the original PR. I'd be happy to merge this if someone can prep it (my knowledge of Carthage is not great).

**Comment by shritekale** [comment]
@danielbmarques In that case, I will reopen this.

**Comment by danielbmarques** [comment]
@shritekale @daveverwer Great, thank you. :)
I don't know much about Carthage myself, I have just begun using it, but they talk about the script I mentioned [here](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos), and it seems to address [precisely the issue you pointed out](http://www.openradar.me/radar?id=6409498411401216).

**Comment by shritekale** [comment]
@danielbmarques @daveverwer  My apologies as I should have been more clear. Apart from the issue you have mentioned, there is a possibility of app rejection because of the private api used in the code. Anyone who consumes the dynamic framework, will be linking against both simulator and device and may submit their apps to the App Store with the framework embedded. Perhaps we need to update the README here to make it clear?

**Comment by danielbmarques** [comment]
@shritekale Oh, I see. Well, I still think it would be worth it. I don't use CocoaPods, so right now I'm copying the whole source code, and when I archive my app I remove it from my Compile Sources and comment it out from the code, and when I need it I add it back to the sources and uncomment it again. Just adding or removing a framework would be a lot more convenient, it just has to be clear in the readme.

**Comment by danielbmarques** [comment]
@shritekale @daveverwer Or maybe [we could do this](http://stackoverflow.com/questions/16943114/how-to-link-framework-only-under-debug-configuration), if I understood correctly?

**Pull request merged**
