### PR TITLE
Support for iOS 17

### PR DESCRIPTION
**Pull request by chrisvasselli**
Adds support for iOS 17, which requires injecting SimulatorStatusMagic into the Springboard process. Explanation is in the updated README.

### CODE REVIEW

**Comment by PerThomasHaga** [comment]
Any idea how it could be possible to get it working when installing this with SPM?

**Review by nrbrook — APPROVED** [review]
As I don’t really use this library any more, I’ll trust that it works and give approval. Great job, looks like it must have been a bit challenging to figure out

**Comment by chrisvasselli** [comment]
> Any idea how it could be possible to get it working when installing this with SPM with use for UI Tests?

I think your best bet for iOS 17 devices is to download the repo separately, and run the included script as described in the README whenever makes sense for your workflow. That's what I'll be doing. Theoretically I could add a script to the scheme or build that would run the appropriate commands, but I think that would be very disruptive, especially since you only really need to run it once per device, not on every app/test launch.

**Comment by chrisvasselli** [comment]
> As I don’t really use this library any more, I’ll trust that it works and give approval. Great job, looks like it must have been a bit challenging to figure out

Thanks Nick! 

Seems like maybe we should get another person on board as a maintainer if you're not using it anymore, at least for reviewing PR's.

@kaidombrowski, @alexkaessner, @PerThomasHaga, @davdroman, @mflint you all 🎉'd, so I'll ask you! Any of you interested in joining the project as a maintainer? It's a very low activity project, basically just updating each year to support the latest OS release. I'm happy to continue doing the research work for the yearly updates, but it'd be good to have someone also using the project to review PR's, incoming issues, help maintain documentation, etc.

**Comment by alexkaessner** [comment]
Thanks for asking @chrisvasselli! As exciting it sounds to support an open source project, I don’t think I’m the right fit for this one. My level of code understanding is too high-level in order to be an actual help at this …

**Comment by davdroman** [comment]
Thanks for the offering @chrisvasselli, but I’m on the same boat as @alexkaessner, and I have other open source commitments that take up most of my time.

**Pull request merged**
