### PR TITLE
property to show/hide battery percentage

### PR DESCRIPTION
**Pull request by mouhassan**
I added a property to show/hide battery percentage.

I had to do a workaround because setting percentage to empty string @"" doesn't work. so I had to set to one space @" " and update the status bar, then set to empty string and update again.

### CODE REVIEW

**Comment by daveverwer** [comment]
Thanks for this @mouhassan, cleaned up and merged.

**Comment by mouhassan** [comment]
Thanks Dave.

I just wanted to highlight that the default behaviour now is that battery percentage is not shown unless the property is set explicitly to TRUE. So, is that ok? or should I change the default behaviour to always show the battery percentage unless explicitly turned off?

**Comment by daveverwer** [comment]
I changed that in my cleanup.

https://github.com/shinydevelopment/SimulatorStatusMagic/commit/45ab03af63b8ab06b516c3ac2d9c1054aaeaeb62

**Comment by mouhassan** [comment]
Thanks Dave for clarification. I'm glad I got a chance to contribute something to this awesome project.

**Comment by daveverwer** [comment]
Thanks for helping!

I just pushed 1.9.3 to Cocoapods so it should be available there soon.

**Pull request merged**
