### PR TITLE
Remove unneeded (trailing) comma and use single app icon

### PR DESCRIPTION
**Pull request by DaniSpringer**
Remove unneeded (trailing) comma

### CODE REVIEW

**Review by chrisvasselli — CHANGES_REQUESTED** [review]
Package.swift change seems fine, can we limit this PR just to that and not modify the gitignore file? Thanks!

**Review by chrisvasselli — APPROVED** [review]
Thanks, looks good!

**Comment by DaniSpringer** [comment]
@chrisvasselli I also changed to use a single app icon size (which has the side effect of fixing related warnings, too), now that Xcode finally supports it.
Please let me know if there is anything I should do to complete this!
Thanks

**Review by chrisvasselli — CHANGES_REQUESTED** [review]
Thanks, appreciate the contributions! I think it makes sense to do that eventually, but I'm concerned that this would require users to be on Xcode 14. I know from my own experience that some companies are cautious about upgrading to the latest Xcode, so I'd rather wait a little bit longer before making this change given that it's only been out a few months.

Can you open a separate PR with this change, and we'll integrate it in, say, 6 months?

**Review by chrisvasselli — APPROVED** [review]

**Comment by DaniSpringer** [comment]
@chrisvasselli is this PR done? Should I close it?
Thanks

**Comment by MortenGregersen** [comment]
Shouldn't this be merged?

**Comment by chrisvasselli** [comment]
Thanks, yes, I think we can safely update this now that it's been a year since Xcode 14 came out. Thanks for the contribution @DaniSpringer!

**Pull request merged**
