### PR TITLE
Implement status bar data overrider for iOS 12b1

### PR DESCRIPTION
**Pull request by cysp**
😃 

I left the changes from iOS 11 as a separate commit for easier review.

### CODE REVIEW

**Comment by daveverwer** [comment]
Thanks for this! I'm seeing a little weirdness when testing this with the iOS 12 beta:

* It seems to switch the Airplane mode icon on
* It causes the Bluetooth headphone icon to appear
* Change the time or carrier doesn't work
* Changing the Network status doesn't work
* Switching Bluetooth to dimmed or connected causes the battery icon to appear next to the headphones.

Thanks so much for making a start on this but I'll not merge it until these are fixed.

**Comment by daveverwer** [comment]
screen shot 2018-06-08 at 07 57 00

**Comment by cysp** [comment]
Odd. I saw _exactly_ those issues before I changed the indexes within `StatusBarItem` but the current branch here allows changing of all of those items on my machine. 🤔

**Comment by cysp** [comment]
screen shot 2018-06-09 at 1 15 19 am

**Comment by daveverwer** [comment]
I just tested it again and I don't quite know what happened but it now works for me. I'd say I was on the wrong branch, but I didn't even change branches before re-running it.

I'll get it merged!

**Comment by daveverwer** [comment]
Thank you for this!

**Pull request merged**
