### PR TITLE
Update README with instructions for UI Test use

### PR DESCRIPTION
**Pull request by apptekstudios**
I've attempted to make it clearer how to use this repository for the two main use cases 1) UI Test automation
2) Manually using the demo app to enable overrides

Let me know what you think :)

### CODE REVIEW

**Review by chrisvasselli — COMMENTED** [review]
Nice, thank you for the contribution! I think this makes things clearer.

The "using in screenshot automation UI tests" section now seems kind of redundant with the "I have a script to take my screenshots, can I automate this?" section. Maybe can you move the information in that old section into the new "using in screenshot automation UI tests" section you created?

**Comment by apptekstudios** [comment]
Hi @chrisvasselli, if I'm not mistaken I've already done this in the PR :)

**Review by chrisvasselli — APPROVED** [review]
@apptekstudios sorry, I just meant the information about setting up with Carthage/CocoaPods/SPM. No worries, it's probably easier for me to just approve this change and then move it as a separate commit. 😊 Thank you for helping make this project more easily approachable!

**Comment by chrisvasselli** [comment]
@apptekstudios Oh I totally misunderstood GitHub's pretty differ for markdown files. You totally did move that info in! Thanks again, this looks all good. 😀

**Pull request merged**
