### PR TITLE
Add network type option (Wi-Fi / GPRS / Edge / 3G / 4G / LTE)

### PR DESCRIPTION
**Pull request by 0xced**
Also, the user interface was rewritten with UIStackView, which required upgrading the deployment target to iOS 9.0.

### CODE REVIEW

**Comment by 0xced** [comment]
Here is a screenshot of the new UI:
simulator screen shot - iphone 6s - 2017-12-20 at 09 12 09

**Comment by daveverwer** [comment]
Thanks. I'm away from home right now but I'll check this and merge it when I get back in a few days.

**Comment by 0xced** [comment]
👍

I just rebased on master so that it’s mergeable.

**Comment by daveverwer** [comment]
👍

**Comment by kenji21** [comment]
looks great, tested and found a small issue (not your fault @0xced) with the bluetooth icon not appearing on iPhone X simulator (I have no idea where it is displayed on the real device)

**Comment by Schaefers** [comment]
It's just displayed in the control center.

**Comment by kenji21** [comment]
OK, thank you for the info

**Comment by daveverwer** [comment]
Thanks very much everyone! Merged. I'll do a release now.

**Comment by daveverwer** [comment]
v2.1 is now released to CocoaPods including this PR.

Merry Christmas 🎄

**Pull request merged**
