### PR TITLE
Added Overrider classes to separately handle simulators < 8.3 and >= 8.3

### LINKED ISSUE #16: Doesn't work in any ios 8.3 simulator
Works from XCode 6.3 in the 8.1 simulators, but not in the 8.3 simulators.  Makes a black box show up on the header, doesn't update time, deosn't remove carrier name.

### PR DESCRIPTION
**Pull request by CraigSiemens**
Fixes #16

### CODE REVIEW

**Comment by hiltonc** [comment]
Yes! Thank you! Be sure to update the podspec too.

**Comment by CraigSiemens** [comment]
What needs to be updated in the podspec?

**Comment by hiltonc** [comment]
The version number.

**Comment by CraigSiemens** [comment]
Updated :)

**Comment by hiltonc** [comment]
w00t! Please merge! :)

**Comment by daveverwer** [comment]
Great PR, thanks very much!

**Pull request merged**
