### PR TITLE
Added support for a custom carrierName

### PR DESCRIPTION
**Pull request by muZZkat**
I wanted to set the carrier name to the company name.

Thanks :-)

### CODE REVIEW

**Comment by KrauseFx** [comment]
I wanted the same thing: https://github.com/shinydevelopment/SimulatorStatusMagic/issues/10 but @daveverwer decided against it :disappointed:

**Comment by daveverwer** [comment]
My apologies, I saw this PR come in and meant to reply to it but I completely forgot about it. Sorry about that!

As @KrauseFx says, it's true that I did not want the ability for custom carrier names. The original intention for this project was to match the status bar Apple uses in all of their marketing material. I don't personally like screenshots with a custom carrier name but it does seem to be something people want to do.

I'm glad this PR doesn't add it to the UI of the app, but I don't see any harm adding it to the API like you've done with this . I'll check this and merge it now.

**Comment by muZZkat** [comment]
Thanks Dave :-)

**Comment by daveverwer** [comment]
No problem! Thanks for contributing.

**Pull request merged**
