### PR TITLE
Fix implicit conversion

### PR DESCRIPTION
**Pull request by igroti**

### CODE REVIEW

**Comment by DaniSpringer** [comment]
Does this need any changes?

**Review by clindsay3 — CHANGES_REQUESTED** [review]
I don't think casting to int is actually an improvement here. If we're looking to make it more clear what we're doing, we could cast to SDStatusBarManagerNetworkType.

**Comment by DaniSpringer** [comment]
@chrisvasselli done!

**Review by clindsay3 — APPROVED** [review]

**Comment by clindsay3** [comment]
Great, thanks for the contributions!!

**Pull request merged**
