### PR TITLE
Added Swift Package Manager support.

### PR DESCRIPTION
**Pull request by joshluongo**
I've added a basic Package.swift file to this can be imported using Swift Package Manager.

This is my first attempt at converting an exisiting project in to a SPM Package. It seems to work for me but I could have missed something :)

### CODE REVIEW

**Review by chrisvasselli — COMMENTED** [review]
@joshluongo I haven't either, but in my brief sanity check it seems to be working. @nrbrook do you have any experience creating swift packages? This all look good to you?

As far as I can tell there's no way to only import swift packages in a debug build, so I'll probably stick to CocoaPods for now, but I see no harm in adding this as an option too.

**Comment by joshluongo** [comment]
> @joshluongo I haven't either, but in my brief sanity check it seems to be working. @nrbrook do you have any experience creating swift packages? This all look good to you?
> 
> 
> 
> As far as I can tell there's no way to only import swift packages in a debug build, so I'll probably stick to CocoaPods for now, but I see no harm in adding this as an option too. 

To my knowledge that is correct, you can't only apply it to debug builds.

I use fastlane so my use case is applying it to the Test Target that generates the screenshots.

**Review by chrisvasselli — APPROVED** [review]
@joshluongo Ah, interesting! I hadn't thought about doing it that way, but that makes a lot of sense, rather than conditionally embedding it in the app itself.

I don't see any harm in accepting this, so let's add it and if anyone runs into any issues, we'll just address those when they come up!

**Comment by daveverwer** [comment]
I wonder if a sentence or two in the README might be useful here, given the subtlety of using it in an SPM-based project. This conversation will get buried now that the PR is closed and as soon as people see a `Package.swift` file, people will potentially add it as a regular dependency without thinking.

**Comment by daveverwer** [comment]
Oh and it can also [have a home here](https://swiftpackageindex.com/shinydevelopment/SimulatorStatusMagic) now, too! 🚀

**Comment by chrisvasselli** [comment]
@daveverwer good call. https://github.com/shinydevelopment/SimulatorStatusMagic/pull/101

**Pull request merged**
